[package]
name = "polyglot_build"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2018"

[dependencies]
codegen = "0.1.3"
glob = "0.3.0"
polyglot = { path = "../polyglot" }
regex = "1"
