[package]
name = "wasm-add"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2018"

[build-dependencies]
polyglot_build = { path = "../../polyglot-build" }

[dependencies]
polyglot = { path = "../../polyglot" }
