[package]
name = "go-render-markdown"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2018"

[[bin]]
name = "go-render-markdown"
path = "main.rs"

[dependencies]
polyglot = { path = "../.." }
